services:
    postgres:
      image: 'postgres:16'
      env_file: ".env"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER$=${POSTGRES_PASSWORD}
      ports:
        - ${POSTGRES_PORTS}
