services:
    postgres:
      image: 'postgres:16'
      environment:
        - 'POSTGRES_DB=recipes'
        - 'POSTGRES_PASSWORD=secret'
        - 'POSTGRES_USER=myuser'
      ports:
        - '5432:5432'
